
DROP DATABASE IF EXISTS ECOMMMVC;

CREATE DATABASE ECOMMMVC;

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PRODUCT_DETAILS;
DROP TABLE IF EXISTS USER_DETAIL;


CREATE TABLE USER_DETAIL
(
  USER_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  USER_FULLNAME VARCHAR(50) NOT NULL,
  USER_EMAIL VARCHAR(255) NOT NULL,
  USER_USERNAME VARCHAR(10) NOT NULL,
  USER_PASSWORD VARCHAR(255) NOT NULL,
  USER_ROLE VARCHAR(10) NOT NULL DEFAULT 'Customer',
  USER_BALANCE BIGINT NOT NULL DEFAULT 100,
);


CREATE TABLE PRODUCT_DETAILS
(
  PRO_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PRO_VENDORID BIGINT NOT NULL,
  PRO_NAME VARCHAR(255) NOT NULL,
  PRO_PRICE FLOAT NOT NULL,
  PRO_QUANTITY INT NOT NULL,
  PRO_CATEGORY VARCHAR(255) NOT NULL,
  FOREIGN KEY (PRO_VENDORID) REFERENCES USER_DETAIL (USER_ID) ON DELETE CASCADE
);


CREATE TABLE CART
(
  CART_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PRO_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  CART_ITEMNAME VARCHAR(255) NOT NULL,
  CART_ITEMQUANTITY INT NOT NULL,
  CART_ITEMPRICE FLOAT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER_DETAIL(USER_ID) ON DELETE CASCADE
);


CREATE TABLE ORDERS
(
  ORDER_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PRO_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  ORDER_TOTALAMOUNT INT NOT NULL,
  ORDER_QUANTITY INT NOT NULL,
  ORDER_STATUS VARCHAR(10) NOT NULL,
  DELIVERY_STATUS VARCHAR(10) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER_DETAIL(USER_ID) ON DELETE CASCADE
);

INSERT INTO USER_DETAIL
  (USER_FULLNAME, USER_EMAIL, USER_USERNAME, USER_PASSWORD)
VALUES
  ('Yeshwanth G', 'yashu@gmail.com', 'Yashu', '1234'),
  ('Prasanna', 'prasanna@gmail.com', 'prasanna', '1234');

INSERT INTO USER_DETAIL
  (USER_FULLNAME, USER_EMAIL, USER_USERNAME, USER_PASSWORD, USER_ROLE)
VALUES
  ('Akshay N A', 'akshay@gmail.com', 'akshay', '1234', 'Vendor');

INSERT INTO PRODUCT_DETAILS
  (PRO_VENDORID, PRO_NAME, PRO_PRICE, PRO_QUANTITY, PRO_CATEGORY)
VALUES
  (3, 'Oneplus 5', 32999, 100, 'Mobile'),
  (3, 'Asus Laptop', 49999, 50, 'Laptop'),
  (3, 'Sony Headphones', 4999, 200, 'Mobile Accessories'),
  (3, 'Apple Watch Series 6', 39999, 20, 'Watch'),
  (3, 'iPhone 12', 69999, 200, 'Mobile'),
  (3, 'Oneplus Y-series TV 32"', 13999, 100, 'TV'),
  (3, 'Gaming PC with RTX 3090', 105999, 10, 'GPU');


